title:
  et: Eesti Avaandmete Portaal
  en: Estonian Open Government Data Portal
greeting:
  et: Eesti Avaandmete Portaal
  en: Estonian Open Government Data Portal
description:
  et: Eesti riigi avaandmete portaali kaudu on igaühel ligipääs avaliku sektori juurdepääsupiiranguteta andmetele koos nende taaskasutamise ja edasijagamise õigusega nii ärilistel kui ka mitteärilistel eesmärkidel.
  en: The Open Data Portal provides a single point of access for general public to unrestricted public sector data with the permission to re-use and redistribute such data for both commercial and non-commercial purposes.
footer_title:
  et: Eesti Avaandmete Portaal
  en: Estonian Open Government Data Portal
footer_description:
  et: Avaandmete portaali sisustatakse Euroopa Liidu struktuuritoetuse toetusskeemist "Infoühiskonna teadlikkuse tõstmine", mida rahastab Euroopa Regionaalarengu Fond.
  en: The Open Data Portal's content is created as part of the EU structural funds' programme "Raising Public Awareness about the Information Society" financed through the EU Regional Development Fund.
alt_tag:
  et: "Euroopa Liit Euroopa Regionaalarengu Fond"
  en: "European Union Regional Developmen Fund"

baseurl:
logo: /img/jkan.png
url: "https://opendata.riik.ee"
domain: https://opendata.riik.ee
# Site theme
jkan_theme: Default

# Authentication
github_client_id:
gatekeeper_host:

# Dataset schema
schema: default

# Nav bar
navigation_et:
  - title: Andmehulgad
    url: /andmehulgad/
  - title: Teabevaldajad
    url: /orgs/
  - title: Rakendused
    url: /rakendused/
  - title: Blogi
    url: /blogi/
  - title: Lisainfo
    url: /lisainfo/
    sublinks:
      - title: Avaandmete Poliitika
        url: /avaandmete-poliitika/
      - title: Juhendid
        url: /juhend/
      - title: Metaandmed
        url: /metaandmed/
      - title: Sündmused ja infomaterjalid
        url: /sundmused-ja-infomaterjalid/
      - title: KKK
        url: /kkk/
      - title: Kontaktid
        url: /kontaktid/
navigation_english:
    - title: Datasets
      url: /en/andmehulgad/
    - title: Publishers
      url: /en/orgs/
    - title: Metadata
      url: /en/metadata/
    - title: Applications
      url: /en/apps/
    - title: Blog
      url: /en/blog/
    - title: More Info
      url: /en/more/
      sublinks:
        - title: Open Data policy
          url: /en/open-data-policy/
        - title: Events and Information Materials
          url: /en/events-and-info-materials/
        - title: FAQ
          url: /en/faq/
        - title: Guidelines
          url: /en/guidelines/
        - title: Contacts
          url: /en/contacts/
        - title: About
          url: /en/about/
#Translations
t:
  en:
    resources: "Resources"
    more: "More Information"
    license: "LICENSE"
    update: "Update Frequency"
    dateissued: "Added to Portal (YYYY-MM-DD)"
    datechanged: "Last Modified (YYYY-MM-DD)"
    contactname: "Contact name"
    contactemail: "Contact email"
  et:
    resources: "Andmefailid"
    more: "Lisainformatsioon"
    license: "Kasutuslitsents"
    update: "Uuendussagedus"
    dateissued: "Lisatud Portaali (YYYY-MM-DD)"
    datechanged: "Viimati muudetud (YYYY-MM-DD)"
    contactname: "Kontakt nimi"
    contactemail: "Kontakt email"

# Collections
collections:
  datasets:
    output: true
    permalink: /andmehulgad/:path/
  datasetsEnglish:
    output: true
    permalink: /en/andmehulgad/:path/
  organizations:
    output: true
  #  permalink: /publishers/:path/
  applications:
    output: true
    permalink: /apps/:path/
  blogi:
    output: true
  #  permalink: /blogi/:path/

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: datasetsEnglish
    values:
      layout: datasetsen
      category: Uncategorized
      organization: N/A  # - scope:
  #     path: ""
  #     type: organizations
  #   values:
  #     layout: organization
  - scope:
      path: "_blogi/et"
    values:
      permalink: "/et/blogi/:title/"
      layout: article
      lang: "et"
  - scope:
      path: "_blogi/en"
    values:
      permalink: "/en/blogi/:title/"
      layout: article
      lang: "en"
  - scope:
      path: "_organizations/et"
    values:
      permalink: "/et/orgs/:title/"
      layout: organization
      lang: "et"
  - scope:
      path: "_organizations/en"
    values:
        permalink: "/en/orgs/:title/"
        layout: organization
        lang: "en"
        #  - scope:
#      path: ""
#      type: applications
#      values:
#      layout: default


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics
google_analytics:
  enabled: true
  code: "UA-59533100-1"

# US Digital Analytics Program - https://analytics.usa.gov
digital_analytics_program:
  enabled: false
  agency: ""
  subagency: ""

# Hypothesis.io - Annotator
hypothesis:
  enabled: false

# Twitter
twittercard:
  enabled: false
  username: "@"

# Open Graph
opengraph:
  enabled: true

plugins:
  - jekyll-sitemap
# feed:
#   collections:
#     - datasets
#     - applications
#     - blogi
#     - organizations



# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md
  - LICENSE
